[package]
name = "serpotter-outbound"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
serpotter-db = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
