pub(crate) struct Rule {
    pub(crate) priority: i32,
    pub(crate) provider: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) tavily_topic: Option<&'static str>,
    pub(crate) firecrawl_categories: Option<&'static [&'static str]>,
    pub(crate) match_mode: Option<&'static str>,
    pub(crate) match_intent: Option<&'static str>,
    pub(crate) match_sources: Option<&'static str>,
}

pub(crate) const RULES: &[Rule] = &[
    Rule {
        priority: 100,
        provider: "xai",
        reason: "Social search",
        tavily_topic: None,
        firecrawl_categories: None,
        match_mode: Some("social"),
        match_intent: None,
        match_sources: Some("x"),
    },
    Rule {
        priority: 90,
        provider: "tavily",
        reason: "News search",
        tavily_topic: Some("news"),
        firecrawl_categories: None,
        match_mode: Some("news"),
        match_intent: None,
        match_sources: None,
    },
    Rule {
        priority: 85,
        provider: "tavily",
        reason: "Document discovery",
        tavily_topic: None,
        firecrawl_categories: None,
        match_mode: Some("docs"),
        match_intent: None,
        match_sources: None,
    },
    Rule {
        priority: 85,
        provider: "tavily",
        reason: "GitHub document discovery",
        tavily_topic: None,
        firecrawl_categories: None,
        match_mode: Some("github"),
        match_intent: None,
        match_sources: None,
    },
    Rule {
        priority: 85,
        provider: "tavily",
        reason: "PDF document discovery",
        tavily_topic: None,
        firecrawl_categories: None,
        match_mode: Some("pdf"),
        match_intent: None,
        match_sources: None,
    },
    Rule {
        priority: 85,
        provider: "tavily",
        reason: "News search (auto-detected)",
        tavily_topic: Some("news"),
        firecrawl_categories: None,
        match_mode: None,
        match_intent: Some("news"),
        match_sources: None,
    },
    Rule {
        priority: 85,
        provider: "tavily",
        reason: "Status search",
        tavily_topic: Some("news"),
        firecrawl_categories: None,
        match_mode: None,
        match_intent: Some("status"),
        match_sources: None,
    },
    Rule {
        priority: 70,
        provider: "tavily",
        reason: "Resource discovery",
        tavily_topic: None,
        firecrawl_categories: None,
        match_mode: None,
        match_intent: Some("resource"),
        match_sources: None,
    },
    Rule {
        priority: 60,
        provider: "tavily",
        reason: "AI answer",
        tavily_topic: None,
        firecrawl_categories: None,
        match_mode: None,
        match_intent: Some("factual"),
        match_sources: None,
    },
    Rule {
        priority: 50,
        provider: "tavily",
        reason: "Research",
        tavily_topic: None,
        firecrawl_categories: None,
        match_mode: Some("research"),
        match_intent: None,
        match_sources: None,
    },
    Rule {
        priority: 10,
        provider: "tavily",
        reason: "Default web search",
        tavily_topic: None,
        firecrawl_categories: None,
        match_mode: None,
        match_intent: None,
        match_sources: Some("web"),
    },
];
