/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthKeysRouteImport } from './routes/_auth/keys'
import { Route as AuthLogsRouteImport } from './routes/_auth/logs'
import { Route as AuthNodesRouteImport } from './routes/_auth/nodes'
import { Route as AuthPlaygroundRouteImport } from './routes/_auth/playground'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthStatsRouteImport } from './routes/_auth/stats'
import { Route as AuthTokensRouteImport } from './routes/_auth/tokens'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKeysRoute = AuthKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogsRoute = AuthLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNodesRoute = AuthNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPlaygroundRoute = AuthPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsRoute = AuthStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTokensRoute = AuthTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/keys': typeof AuthKeysRoute
  '/logs': typeof AuthLogsRoute
  '/nodes': typeof AuthNodesRoute
  '/playground': typeof AuthPlaygroundRoute
  '/settings': typeof AuthSettingsRoute
  '/stats': typeof AuthStatsRoute
  '/tokens': typeof AuthTokensRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/keys': typeof AuthKeysRoute
  '/logs': typeof AuthLogsRoute
  '/nodes': typeof AuthNodesRoute
  '/playground': typeof AuthPlaygroundRoute
  '/settings': typeof AuthSettingsRoute
  '/stats': typeof AuthStatsRoute
  '/tokens': typeof AuthTokensRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/keys': typeof AuthKeysRoute
  '/_auth/logs': typeof AuthLogsRoute
  '/_auth/nodes': typeof AuthNodesRoute
  '/_auth/playground': typeof AuthPlaygroundRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/stats': typeof AuthStatsRoute
  '/_auth/tokens': typeof AuthTokensRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/keys'
    | '/logs'
    | '/nodes'
    | '/playground'
    | '/settings'
    | '/stats'
    | '/tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/keys'
    | '/logs'
    | '/nodes'
    | '/playground'
    | '/settings'
    | '/stats'
    | '/tokens'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard'
    | '/_auth/keys'
    | '/_auth/logs'
    | '/_auth/nodes'
    | '/_auth/playground'
    | '/_auth/settings'
    | '/_auth/stats'
    | '/_auth/tokens'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/keys': {
      id: '/_auth/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthKeysRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/logs': {
      id: '/_auth/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/nodes': {
      id: '/_auth/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AuthNodesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/playground': {
      id: '/_auth/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthPlaygroundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats': {
      id: '/_auth/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthStatsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tokens': {
      id: '/_auth/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AuthTokensRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthKeysRoute: typeof AuthKeysRoute
  AuthLogsRoute: typeof AuthLogsRoute
  AuthNodesRoute: typeof AuthNodesRoute
  AuthPlaygroundRoute: typeof AuthPlaygroundRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthStatsRoute: typeof AuthStatsRoute
  AuthTokensRoute: typeof AuthTokensRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthKeysRoute: AuthKeysRoute,
  AuthLogsRoute: AuthLogsRoute,
  AuthNodesRoute: AuthNodesRoute,
  AuthPlaygroundRoute: AuthPlaygroundRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthStatsRoute: AuthStatsRoute,
  AuthTokensRoute: AuthTokensRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
